name: difwa
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.8.0
  cloud_firestore:
  firebase_auth:
  firebase_storage:
  get: ^4.6.6
  flutter_svg: any
  intl: ^0.19.0
  lottie: ^3.1.3
  flutter_date_pickers: ^0.4.3
  table_calendar: ^3.1.3
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/bottle.svg
    - assets/images/tiffine.svg
    - assets/images/food.svg
    - assets/images/samosa.jpeg
    - assets/images/login.svg
    - assets/posters/1.png
    - assets/posters/1.jpg
    - assets/posters/5.png
    - assets/posters/tiffin.svg
    - assets/images/otp.svg
    - assets/images/logo.svg
    - assets/images/error.svg
    - assets/images/sublogo.svg
    - assets/images/logowithtitle.svg
    - assets/audio/order.mp3
    - assets/images/splashbg.svg
    - assets/images/cardvector.svg
    - assets/lottie/loader.json
    - assets/images/dummyimg.svg
    - assets/frames/storeformframe.svg
    - assets/images/stonb1.svg
    - assets/images/stonb2.svg
    - assets/images/stonb3.svg
    - assets/images/stonb11.svg
    - assets/images/stonb22.svg
    - assets/images/stonb33.svg
    - assets/images/water.jpg
    - assets/images/bottal.jpg
    - assets/images/gb.png
    - assets/images/default_avatar.png
    - assets/images/difwalogo.svg
    - assets/images/difwalogo2.svg
    - assets/elements/splash.svg
    - assets/elements/homecard.svg
    - assets/elements/homecardbottle.svg
    - assets/bgimage/top.svg
    - assets/bgimage/bottom.svg
    - assets/logos/difwalogo1.svg
