name: difwa
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: 
  cloud_firestore:
  firebase_auth:
  firebase_storage:
  get: ^4.6.6
  order_tracker:
  order_tracker_zen:
  flutter_svg: any
  intl: ^0.19.0
  lottie: ^3.3.1
  flutter_date_pickers: ^0.4.3
  table_calendar: ^3.1.3
  url_launcher: ^6.3.1
  carousel_slider:
  app_badge_plus:
  smooth_page_indicator: ^1.0.0
  country_code_picker: ^3.0.0
  flutter_animate: ^4.5.2
  flutter_form_builder: ^9.7.0
  flutter_staggered_animations: ^1.1.1
  flutter_spinkit: ^5.2.1
  fluttertoast: ^8.2.12
  dio: ^5.8.0+1
  country_picker: ^2.0.0
  app_links: ^6.4.0
  icons_plus: ^5.0.0
  animated_icon: ^0.0.9
  image_picker: ^1.1.2
  google_fonts: ^6.2.1
  webview_flutter: ^4.10.0
  webview_flutter_android: ^4.3.4
  webview_flutter_wkwebview: ^3.18.4
  logger: ^2.5.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  
  


flutter:
  uses-material-design: true

  assets:
    - assets/images/bottle.svg
    - assets/images/tiffine.svg
    - assets/images/food.svg
    - assets/images/samosa.jpeg
    - assets/images/login.svg
    - assets/posters/1.png
    - assets/posters/1.jpg
    - assets/posters/5.png
    - assets/posters/tiffin.svg
    - assets/images/
    - assets/images/otp.svg
    - assets/images/logo.svg
    - assets/images/error.svg
    - assets/images/sublogo.svg
    - assets/images/logowithtitle.svg
    - assets/audio/order.mp3
    - assets/images/splashbg.svg
    - assets/images/cardvector.svg
    - assets/lottie/loader.json
    - assets/images/dummyimg.svg
    - assets/frames/storeformframe.svg
    - assets/images/stonb1.svg
    - assets/images/stonb2.svg
    - assets/images/stonb3.svg
    - assets/images/stonb11.svg
    - assets/images/stonb22.svg
    - assets/images/stonb33.svg
    - assets/images/water.jpg
    - assets/images/dlogo.svg
    - assets/images/bottal.jpg
    - assets/images/gb.png
    - assets/images/default_avatar.png
    - assets/images/difwalogo.svg
    - assets/images/difwalogo2.svg
    - assets/elements/splash.svg
    - assets/elements/homecard.svg
    - assets/elements/homecardbottle.svg
    - assets/bgimage/top.svg
    - assets/bgimage/bottom.svg
    - assets/logos/difwalogo1.svg
    - assets/scollerimg/image0.jpg
    - assets/scollerimg/image1.png
    - assets/scollerimg/image2.png
    - assets/cardbg.png
    - assets/cardbg1.png
    - assets/cardbg2.png
    - assets/cardbg3.png
    - assets/cardbg4.png
    - assets/cardbg5.png
    - assets/cardbg6.png
    - assets/cardbg7.png
    - assets/cardbg8.png
    - assets/button/drop.png
    - assets/button/dropd.png
    - assets/button/blbg.png
    - assets/button/trbg.png
    - assets/icons/iconbg.svg
    - assets/icons/iconbg.png
    - assets/icons/
    - assets/bgimage.png
    - assets/imagebg.png

